CREATE DEFINER=`root`@`localhost` PROCEDURE `SP_COMPLIANCE_GET_BY_ID`(
	IN P_COMPLIANCE_ID INT
)
BEGIN
    SELECT 
		CP.ID,
		CP.NAME,
        CP.TYPE
	FROM COMPLIANCE_POLICY CP
    WHERE CP.ID = P_COMPLIANCE_ID;
END