CREATE DEFINER=`root`@`localhost` PROCEDURE `SP_COMPLIANCE_RULE_SECTOR_TRANSITION_GET_BY_POLICY_ID`(
    IN P_POLICY_ID INT
)
BEGIN
    SELECT
		CP.ID AS PolicyId,
        CP.NAME AS PolicyName,
        (
			SELECT JSON_ARRAYAGG(
				JSON_OBJECT(
					'Id', CRST.ID,
					'SectorId', CRST.SECTOR_ID,
					'OrderIndex', CRST.ORDER_INDEX,
					'MinTime', CRST.MIN_TIME,
					'MaxTime', CRST.MAX_TIME
				)
			)
			FROM COMPLIANCE_RULE_SECTOR_TRANSITION CRST
			WHERE CRST.POLICY_ID = P_POLICY_ID
			ORDER BY CRST.ORDER_INDEX
        ) AS Rules
	FROM COMPLIANCE_POLICY CP
    WHERE CP.ID = P_POLICY_ID;
END