CREATE DEFINER=`root`@`localhost` PROCEDURE `SP_COMPLIANCE_VIOLATION_GET_BY_ID`(
    IN P_COMPLIANCE_VIOLATION_ID INT
    
)
BEGIN
    SELECT
		P.ID AS PersonId,
		P.NAME AS PersonName,
        P.IMAGE_PATH AS PersonPhoto,
        CL.ENTERED_AT,
        CL.EXITED_AT,
        CP.TYPE PolicyType,
		CV.VIOLATION_TYPE
    FROM COMPLIANCE_VIOLATION CV
    LEFT JOIN PERSON P ON P.ID = CV.PERSON_ID
    LEFT JOIN COMPLIANCE_POLICY CP ON CP.ID = CV.POLICY_ID
    LEFT JOIN COMPLIANCE_LOG CL ON CL.ID = CV.LOG_ID
    WHERE CV.ID = P_COMPLIANCE_VIOLATION_ID;
END