CREATE DEFINER=`root`@`localhost` PROCEDURE `SP_COMPLIANCE_RULE_SECTOR_TRANSITION_CREATE`(
    IN P_POLICY_NAME VARCHAR(100),
    IN P_RULE_JSON JSON
)
BEGIN
    DECLARE ERRO INT DEFAULT 0;
    DECLARE MENSAGEM VARCHAR(100) DEFAULT 'SUCESSO';
    DECLARE NEW_ID INT DEFAULT 0;

    DECLARE EXIT HANDLER FOR SQLEXCEPTION
    BEGIN
        ROLLBACK;
        GET DIAGNOSTICS CONDITION 1 MENSAGEM = MESSAGE_TEXT; -- Pega o erro real do MySQL
        SET ERRO = 1;
        SELECT NEW_ID AS Id, ERRO, MENSAGEM AS Mensagem;
    END;

    START TRANSACTION;

        INSERT INTO COMPLIANCE_POLICY (NAME, TYPE)
        VALUES (P_POLICY_NAME, 'SECTOR_TRANSITION');

        SET NEW_ID = LAST_INSERT_ID();
        
        INSERT INTO COMPLIANCE_RULE_SECTOR_TRANSITION (POLICY_ID, SECTOR_ID, ORDER_INDEX, MIN_TIME, MAX_TIME)
		SELECT 
			NEW_ID,
			SECTOR_ID,
			ORDER_INDEX,
			MIN_TIME,
			MAX_TIME
		FROM JSON_TABLE(P_RULE_JSON, '$[*]' COLUMNS (
			SECTOR_ID    INT PATH '$.sectorId',
			ORDER_INDEX  INT PATH '$.orderIndex',
			MIN_TIME     INT PATH '$.minTime',
			MAX_TIME     INT PATH '$.maxTime'
		)) AS STEPS;
        
    COMMIT;

    SELECT 
        ERRO AS Erro,
        MENSAGEM AS Mensagem,
        NEW_ID AS Id;
END