CREATE DEFINER=`root`@`localhost` PROCEDURE `SP_COMPLIANCE_VIOLATION_GET_ALL`(
	IN P_PAGE_NUMBER INT,
    IN P_PAGE_SIZE INT
)
BEGIN
	DECLARE V_OFFSET_VALUE INT;
    SET V_OFFSET_VALUE  = (P_PAGE_NUMBER - 1) * P_PAGE_SIZE;

    SELECT
		CV.ID,
		P.ID AS PersonId,
		P.NAME AS PersonName,
		P.IMAGE_PATH AS PersonPhoto,
        S.ID AS SectorId,
        S.NAME AS SectorName,
        CL.ENTERED_AT,
        CL.EXITED_AT,
        CP.ID AS PolicyId,
        CP.NAME AS PolicyName,
        CP.TYPE AS PolicyType,
		CV.VIOLATION_TYPE,
        CV.CREATED_AT
    FROM COMPLIANCE_VIOLATION CV
    LEFT JOIN PERSON P ON P.ID = CV.PERSON_ID
    LEFT JOIN COMPLIANCE_POLICY CP ON CP.ID = CV.POLICY_ID
    LEFT JOIN COMPLIANCE_LOG CL ON CL.ID = CV.LOG_ID
    LEFT JOIN SECTOR S ON S.ID = CL.SECTOR_ID
    ORDER BY L.CREATED_AT DESC
    LIMIT P_PAGE_SIZE OFFSET V_OFFSET_VALUE;
END