CREATE DEFINER=`root`@`localhost` PROCEDURE `SP_COMPLIANCE_LOG_CREATE`(
    IN P_PERSON_ID INT,
    IN P_SECTOR_ID INT,
    IN P_EVENT_TYPE VARCHAR(50),
    IN P_IDENTIFIED_AT DATETIME
    
)
BEGIN
    DECLARE ERRO INT DEFAULT 0;
    DECLARE MENSAGEM VARCHAR(100) DEFAULT 'SUCESSO';
    DECLARE NEW_ID INT DEFAULT 0;

    DECLARE EXIT HANDLER FOR SQLEXCEPTION
    BEGIN
        ROLLBACK;
        GET DIAGNOSTICS CONDITION 1 MENSAGEM = MESSAGE_TEXT; -- Pega o erro real do MySQL
        SET ERRO = 1;
        SELECT NEW_ID AS Id, ERRO, MENSAGEM AS Mensagem;
    END;

    START TRANSACTION;

        INSERT INTO COMPLIANCE_LOG (PERSON_ID, SECTOR_ID, EVENT_TYPE, IDENTIFIED_AT)
        VALUES (P_PERSON_ID, P_SECTOR_ID, P_EVENT_TYPE, P_IDENTIFIED_AT);

		SET NEW_ID = LAST_INSERT_ID();
        
    COMMIT;

    SELECT 
        ERRO AS Erro,
        MENSAGEM AS Mensagem,
        NEW_ID AS Id;
END