CREATE DEFINER=`root`@`localhost` PROCEDURE `SP_COMPLIANCE_POLICY_CREATE`(
    IN P_NAME VARCHAR(100)
)
BEGIN
    DECLARE ERRO INT DEFAULT 0;
    DECLARE MENSAGEM VARCHAR(100) DEFAULT 'SUCESSO';
    DECLARE NEW_ID INT DEFAULT 0;

    DECLARE EXIT HANDLER FOR SQLEXCEPTION
	BEGIN
		ROLLBACK;

		SELECT 
			1 AS Erro,
			'ERRO AO INSERIR O COMPLIANCE' AS Mensagem,
			0 AS Id;
	END;

    START TRANSACTION;

        INSERT INTO camera (NAME)
        VALUES (P_NAME);

        SET NEW_ID = LAST_INSERT_ID();
    COMMIT;

    SELECT 
        ERRO AS Erro,
        MENSAGEM AS Mensagem,
        NEW_ID AS Id;
END