CREATE DEFINER=`root`@`localhost` PROCEDURE `SP_COMPLIANCE_VIOLATION_CREATE`(
    IN P_LOG_ID INT,
    IN P_POLICY_ID INT,
    IN P_PERSON_ID INT,
    IN P_VIOLATION_TYPE INT
    
)
BEGIN
    DECLARE ERRO INT DEFAULT 0;
    DECLARE MENSAGEM VARCHAR(100) DEFAULT 'SUCESSO';
    DECLARE NEW_ID INT DEFAULT 0;

    DECLARE EXIT HANDLER FOR SQLEXCEPTION
    BEGIN
        ROLLBACK;
        GET DIAGNOSTICS CONDITION 1 MENSAGEM = MESSAGE_TEXT;
        SET ERRO = 1;
        SELECT NEW_ID AS Id, ERRO, MENSAGEM AS Mensagem;
    END;

    START TRANSACTION;
		
        INSERT INTO COMPLIANCE_VIOLATION (LOG_ID, POLICY_ID, PERSON_ID, VIOLATION_TYPE)
        VALUES (P_LOG_ID, P_POLICY_ID, P_PERSON_ID, P_VIOLATION_TYPE);
		
        SET NEW_ID = LAST_INSERT_ID();
        
    COMMIT;

    SELECT 
        ERRO AS Erro,
        MENSAGEM AS Mensagem,
        NEW_ID AS Id;
END