CREATE DEFINER=`root`@`localhost` PROCEDURE `SP_COMPLIANCE_LOG_CREATE`(
    IN P_PERSON_ID INT,
    IN P_SECTOR_ID INT,
    IN P_IDENTIFIED_AT DATETIME
    
)
BEGIN
    DECLARE ERRO INT DEFAULT 0;
    DECLARE MENSAGEM VARCHAR(100) DEFAULT 'SUCESSO';
    DECLARE NEW_ID INT DEFAULT 0;
    DECLARE V_LOG_ID INT DEFAULT NULL;

    DECLARE EXIT HANDLER FOR SQLEXCEPTION
    BEGIN
        ROLLBACK;
        GET DIAGNOSTICS CONDITION 1 MENSAGEM = MESSAGE_TEXT; -- Pega o erro real do MySQL
        SET ERRO = 1;
        SELECT NEW_ID AS Id, ERRO, MENSAGEM AS Mensagem;
    END;

    START TRANSACTION;

		SELECT ID
        INTO V_LOG_ID
        FROM COMPLIANCE_LOG
        WHERE SECTOR_ID = P_SECTOR_ID 
			AND PERSON_ID = P_PERSON_ID
            AND EXITED_AT IS NULL
        LIMIT 1;
        
        IF V_LOG_ID IS NULL THEN
			INSERT INTO COMPLIANCE_LOG (PERSON_ID, SECTOR_ID, ENTERED_AT)
			VALUES (P_PERSON_ID, P_SECTOR_ID, P_IDENTIFIED_AT);
            
            SET NEW_ID = LAST_INSERT_ID();
		ELSE
			UPDATE COMPLIANCE_LOG
            SET EXITED_AT = P_IDENTIFIED_AT
            WHERE ID = V_LOG_ID;
            
            SET NEW_ID = V_LOG_ID;
		END IF;
    COMMIT;

    SELECT 
        ERRO AS Erro,
        MENSAGEM AS Mensagem,
        NEW_ID AS Id;
END