CREATE DEFINER=`root`@`localhost` PROCEDURE `SP_COMPLIANCE_LOG_GET_BY_ID`(
    IN P_COMPLIANCE_LOG_ID INT
)
BEGIN
    SELECT
		CL.ID,
        CL.PERSON_ID,
        CL.SECTOR_ID,
        CL.ENTERED_AT,
        CL.EXITED_AT
	FROM COMPLIANCE_LOG CL
    WHERE CL.ID = P_COMPLIANCE_LOG_ID;
END