CREATE DEFINER=`root`@`localhost` PROCEDURE `SP_COMPLIANCE_GET_BY_DEVICE`(
	IN P_SECTOR_ID INT
)
BEGIN
    SELECT DISTINCT 
		CP.ID, 
        CP.NAME, 
        (CP.TYPE - 1) AS Rule
    FROM COMPLIANCE_POLICY CP
    INNER JOIN COMPLIANCE_RULE_SECTOR_TRANSITION CRT ON CRT.POLICY_ID = CP.ID
    WHERE CRT.SECTOR_ID = P_SECTOR_ID
    AND CP.TYPE = 'SECTOR_TRANSITION';
END