CREATE DEFINER=`root`@`localhost` PROCEDURE `SP_COMPLIANCE_RULE_SECTOR_TRANSITION_GET_BY_POLICY_ID`(
    IN P_POLICY_ID INT
)
BEGIN
    SELECT
		CRST.SECTOR_ID,
        CRST.ORDER_INDEX,
        MIN_TIME,
        MAX_TIME
    FROM COMPLIANCE_RULE_SECTOR_TRANSITION CRST
    WHERE CRST.POLICY_ID = P_POLICY_ID;
END