CREATE DEFINER=`root`@`localhost` PROCEDURE `SP_COMPLIANCE_LOG_GET_BY_PERSON`(
    IN P_PERSON_ID INT
)
BEGIN
    SELECT
		CL.ID,
        CL.PERSON_ID,
        CL.SECTOR_ID,
        CL.ENTERED_AT,
        CL.EXITED_AT
	FROM COMPLIANCE_LOG CL
    WHERE CL.PERSON_ID = P_PERSON_ID AND DATE(ENTERED_AT) = CURDATE();
END