CREATE DEFINER=`root`@`localhost` PROCEDURE `SP_CAMERA_CONFIG_INCIDENT_RECORDING_GET_BY_CAMERA_ID`(
	IN P_CAMERA_ID INT
)
BEGIN
	SELECT
		MAC_ADDRESS AS MacAddress
	FROM CAMERA
    WHERE ID = P_CAMERA_ID;
END