CREATE DEFINER=`root`@`localhost` PROCEDURE `SP_CAMERA_CONFIG_DWELL_TIME_MONITORING_CREATE`(
	IN P_CAMERA_ID INT,
    IN P_MAX_DWELL_TIME_MINUTES INT,
    IN P_MAX_NON_IDENTIFICATION_TIME_MINUTES INT
)
BEGIN
	DECLARE ERRO INT DEFAULT 0;
	DECLARE MENSAGEM VARCHAR(100) DEFAULT 'SUCESSO';
	DECLARE NEW_ID INT DEFAULT 0;

	DECLARE EXIT HANDLER FOR SQLEXCEPTION
	BEGIN
		ROLLBACK;

		SELECT 
			1 AS Erro,
			'ERRO AO INSERIR AS CONFIGURAÇÕES DE CONTROLE DE PERMANENCIA DA CAMERA' AS Mensagem,
			0 AS Id;
	END;
    
    START TRANSACTION;

        INSERT INTO camera_config_dwell_time_monitoring (CAMERA_ID, MAX_DWELL_TIME_MINUTES, MAX_NON_IDENTIFICATION_TIME_MINUTES)
        VALUES (P_CAMERA_ID, P_MAX_DWELL_TIME_MINUTES, P_MAX_NON_IDENTIFICATION_TIME_MINUTES);

        SET NEW_ID = LAST_INSERT_ID();
    COMMIT;

    SELECT 
        ERRO AS Erro,
        MENSAGEM AS Mensagem,
        NEW_ID AS Id;
END