CREATE DEFINER=`root`@`localhost` PROCEDURE `SP_CAMERA_CONFIG_DWELL_TIME_MONITORING_GET_BY_CAMERA_ID`(
	IN P_CAMERA_ID INT
)
BEGIN
	SELECT
		ID,
        CAMERA_ID AS CameraId,
        MAX_DWELL_TIME_MINUTES AS MaxDwellTimeMinutes,
        MAX_NON_IDENTIFICATION_TIME_MINUTES AS MaxNonIdentificationTimeMinutes
	FROM CAMERA_CONFIG_DWELL_TIME_MONITORING
    WHERE CAMERA_ID = P_CAMERA_ID;
END