CREATE DEFINER=`root`@`localhost` PROCEDURE `SP_CAMERA_GET_ALL_CACHE`()
BEGIN
    SELECT
		C.ID,
		C.SECTOR_ID,
		(
			SELECT JSON_ARRAYAGG(
				JSON_OBJECT(
					'Id', CF.FEATURE_ID
				)
			)
			FROM CAMERA_FEATURE CF
			WHERE CF.CAMERA_ID = C.ID AND CF.IS_ACTIVE = 1
		) AS Features

	FROM CAMERA C
	WHERE C.IS_ACTIVE = 1;
END