CREATE DEFINER=`root`@`localhost` PROCEDURE `SP_CAMERA_CONFIG_DWELL_TIME_MONITORING_UPDATE`(
	IN P_ID INT,
    IN P_MAX_DWELL_TIME_MINUTES INT,
    IN P_MAX_NON_IDENTIFICATION_TIME_MINUTES INT
)
BEGIN
	DECLARE ERRO INT DEFAULT 0;
    DECLARE MENSAGEM VARCHAR(100) DEFAULT 'SUCESSO';
    
    DECLARE EXIT HANDLER FOR SQLEXCEPTION
	BEGIN
		ROLLBACK;

		SELECT 
			1 AS Erro,
			'ERRO AO ATUALIZAR OS DADOS DO REGISTRO DE INCIDENTE DA CAMERA' AS Mensagem,
			0 AS Id;
	END;
    
    START TRANSACTION;

        UPDATE CAMERA_CONFIG_DWELL_TIME_MONITORING
        SET
			MAX_DWELL_TIME_MINUTES = P_MAX_DWELL_TIME_MINUTES,
            MAX_NON_IDENTIFICATION_TIME_MINUTES = P_MAX_NON_IDENTIFICATION_TIME_MINUTES
		WHERE ID = P_ID;
        
	COMMIT;

    SELECT 
        ERRO AS Erro,
        MENSAGEM AS Mensagem,
        P_ID AS Id;
END