CREATE DEFINER=`root`@`localhost` PROCEDURE `SP_CAMERA_INCIDENT_RECORDING_UPDATE`(
	IN P_CAMERA_ID INT,
    IN P_MAC_ADDRESS VARCHAR(100)
)
BEGIN
	DECLARE ERRO INT DEFAULT 0;
    DECLARE MENSAGEM VARCHAR(100) DEFAULT 'SUCESSO';
    
    DECLARE EXIT HANDLER FOR SQLEXCEPTION
	BEGIN
		ROLLBACK;

		SELECT 
			1 AS Erro,
			'ERRO AO ATUALIZAR OS DADOS DO REGISTRO DE INCIDENTE DA CAMERA' AS Mensagem,
			0 AS Id;
	END;
    
    START TRANSACTION;

        UPDATE CAMERA
        SET
			MAC_ADDRESS = P_MAC_ADDRESS
		WHERE ID = P_CAMERA_ID;
        
	COMMIT;

    SELECT 
        ERRO AS Erro,
        MENSAGEM AS Mensagem,
        P_ID AS Id;
END