CREATE DEFINER=`root`@`localhost` PROCEDURE `SP_CAMERA_CREATE`(
    IN P_NAME VARCHAR(100),
    IN P_CONNECTION VARCHAR(255),
    IN P_SECTOR_ID INT
)
BEGIN
    DECLARE ERRO INT DEFAULT 0;
    DECLARE MENSAGEM VARCHAR(100) DEFAULT 'SUCESSO';
    DECLARE NEW_ID INT DEFAULT 0;

    DECLARE EXIT HANDLER FOR SQLEXCEPTION
	BEGIN
		ROLLBACK;

		SELECT 
			1 AS Erro,
			'ERRO AO INSERIR CAMERA' AS Mensagem,
			0 AS Id;
	END;

    START TRANSACTION;

		INSERT INTO DEVICE (NAME, TYPE, ORIGIN_SECTOR_ID)
        VALUES (P_NAME, 'CAMERA', P_SECTOR_ID);
        
        SET NEW_ID = LAST_INSERT_ID();

        INSERT INTO CAMERA (DEVICE_ID, CONNECTION)
        VALUES (NEW_ID, P_CONNECTION);

        SET NEW_ID = LAST_INSERT_ID();
    COMMIT;

    SELECT 
        ERRO AS Erro,
        MENSAGEM AS Mensagem,
        NEW_ID AS Id;
END