CREATE DEFINER=`root`@`localhost` PROCEDURE `SP_INCIDENT_RECORDING_GET_ALL_LOGS`(
	IN P_PAGE_NUMBER INT,
    IN P_PAGE_SIZE INT
)
BEGIN
	DECLARE V_OFFSET_VALUE INT;
    SET V_OFFSET_VALUE  = (P_PAGE_NUMBER - 1) * P_PAGE_SIZE;

	SELECT
		IR.ID,
		S.NAME AS Sector,
        IR.INCIDENT_TIME AS IncidentTime,
        IR.STATUS,
        IR.FILE_NAME AS FileName,
        IR.CREATED_AT,
        CASE 
			WHEN COUNT(IRP.INCIDENT_RECORDING_ID) = 0 THEN NULL
				ELSE JSON_ARRAYAGG(
					JSON_OBJECT(
						"Id", P.ID,
						"Name", P.NAME,
						"ImagePath", P.IMAGE_PATH,
						"SeenAt", DATE_FORMAT(IRP.SEEN_AT, '%Y-%m-%dT%H:%i:%s.%fZ'),
                        "VideoOffsetSeconds", IRP.VIDEO_OFFSET_SECONDS
					)
				) 
			END AS Persons
    FROM INCIDENT_RECORDING IR
    LEFT JOIN CAMERA C ON C.ID = IR.CAMERA_ID
    LEFT JOIN SECTOR S ON S.ID = C.SECTOR_ID
    LEFT JOIN INCIDENT_RECORDING_PERSON IRP ON IRP.INCIDENT_RECORDING_ID = IR.ID
    LEFT JOIN PERSON P ON P.ID = IRP.PERSON_ID
    GROUP BY
		IR.ID,
		S.NAME,
        IR.INCIDENT_TIME,
        IR.STATUS,
        IR.FILE_NAME,
        IR.CREATED_AT
    ORDER BY 
		IR.CREATED_AT
	LIMIT P_PAGE_SIZE OFFSET V_OFFSET_VALUE;
END