CREATE DEFINER=`root`@`localhost` PROCEDURE `SP_CAMERA_ROI_DELETE`(
	IN P_CAMERA_ROI_ID INT
)
BEGIN
	DECLARE ERRO INT DEFAULT 0;
    DECLARE MENSAGEM VARCHAR(100) DEFAULT 'SUCESSO';
    DECLARE DELETED_ID INT DEFAULT 0;
    
    DECLARE EXIT HANDLER FOR SQLEXCEPTION
    BEGIN
		ROLLBACK;
        SELECT
			1 AS ERRO,
            'ERRO AO EXCLUIR GRUPO DE NOTIFICAÇÃO' AS MENSAGEM,
            0 AS ID;  
		END;
    
    START TRANSACTION;
		DELETE FROM CAMERA_ROI CR
        WHERE CR.ID = P_CAMERA_ROI_ID;
    COMMIT;
    
    SELECT
		ERRO,
        MENSAGEM,
		P_CAMERA_ROI_ID AS ID;
END