CREATE DEFINER=`root`@`localhost` PROCEDURE `SP_CAMERA_ROI_UPDATE`(
	IN P_CAMERA_ROI_ID INT,
    IN P_COORDINATES_JSON JSON,
    IN P_IS_ACTIVE TINYINT
)
BEGIN
	DECLARE ERRO INT DEFAULT 0;
    DECLARE MENSAGEM VARCHAR(100) DEFAULT 'SUCESSO';
    
    DECLARE EXIT HANDLER FOR SQLEXCEPTION
	BEGIN
		ROLLBACK;

		SELECT 
			1 AS Erro,
			'ERRO AO INSERIR CAMERA' AS Mensagem,
			0 AS Id;
	END;
    
    START TRANSACTION;

        UPDATE CAMERA_ROI
        SET
			COORDINATES_JSON = P_COORDINATES_JSON,
            IS_ACTIVE = P_IS_ACTIVE
		WHERE ID = P_CAMERA_ROI_ID;
        
	COMMIT;

    SELECT 
        ERRO AS Erro,
        MENSAGEM AS Mensagem,
        P_ID AS Id;
END