CREATE DEFINER=`root`@`localhost` PROCEDURE `SP_CAMERA_ROI_GET_BY_CAMERA_ID`(
	IN P_CAMERA_ID INT
)
BEGIN
    SELECT 
		CR.ID,
        CR.CAMERA_ID AS CameraId,
        CR.ROI_TYPE AS RoiType,
        CR.COORDINATES_JSON AS Coordinates,
        CR.IS_ACTIVE AS IsActive
	FROM CAMERA_ROI CR
    WHERE CR.CAMERA_ID = P_CAMERA_ID;
END