CREATE DEFINER=`root`@`localhost` PROCEDURE `SP_DWELL_TIME_MONITORING_GET_DETAILS_BY_CAMERA_ID`(
	IN P_CAMERA_ID INT
)
BEGIN
	SELECT
		P.NAME AS PersonName,
        P.IMAGE_PATH AS ImagePath,
		DTM.ENTERED_AT AS EnteredAt,
        DTM.EXITED_AT AS ExitedAt
	FROM DWELL_TIME_MONITORING DTM
    LEFT JOIN PERSON P ON P.ID = DTM.PERSON_ID
    WHERE DTM.CAMERA_ID = P_CAMERA_ID;
END