CREATE DEFINER=`root`@`localhost` PROCEDURE `SP_ACCESS_VIOLATION_GET_DETAIL`(
	IN P_PERSON_ID INT,
    IN P_SECTOR_ID INT
)
BEGIN
    SELECT
		P.NAME AS Person,
        S.NAME AS Sector,
        (
			SELECT JSON_ARRAYAGG(
				JSON_OBJECT(
					"Email", NGE.EMAIL
                )
			)
            FROM SECTOR_NOTIFICATION_GROUP SNG
            LEFT JOIN NOTIFICATION_GROUP NG ON NG.ID = SNG.NOTIFICATION_GROUP_ID
            LEFT JOIN NOTIFICATION_GROUP_EMAIL NGE ON NGE.NOTIFICATION_GROUP_ID = NG.ID
            WHERE SNG.SECTOR_ID = P_SECTOR_ID
        ) AS Emails
	FROM PERSON P
	INNER JOIN SECTOR S ON S.ID = P_SECTOR_ID
    WHERE P.ID = P_PERSON_ID;
END