CREATE DEFINER=`root`@`localhost` PROCEDURE `SP_ACCESS_LEVEL_CREATE`(
	IN P_NAME VARCHAR(100),
    IN P_SECTORS_JSON JSON,
    IN P_ACCESS_SCHEDULE_ID INT
)
BEGIN
	DECLARE ERRO INT DEFAULT 0;
    DECLARE MENSAGEM VARCHAR(100) DEFAULT 'SUCESSO';
    DECLARE NEW_ID INT DEFAULT 0;

    DECLARE EXIT HANDLER FOR SQLEXCEPTION
    BEGIN
        SET ERRO = 1;
        SET MENSAGEM = 'ERRO AO INSERIR O NÍVEL DE ACESSO';
        ROLLBACK;
    END;
    
    START TRANSACTION;
		INSERT INTO ACCESS_LEVEL (NAME, ACCESS_SCHEDULE_ID)
        VALUES (P_NAME, P_ACCESS_SCHEDULE_ID);
        
        SET NEW_ID = LAST_INSERT_ID();
        
        INSERT INTO ACCESS_LEVEL_SECTOR (ACCESS_LEVEL_ID, SECTOR_ID)
        SELECT NEW_ID, jt.sector_id
        FROM JSON_TABLE(P_SECTORS_JSON, '$[*]' COLUMNS (sector_id INT PATH '$')) jt;
    COMMIT;
    
    SELECT 
        ERRO AS Erro,
        MENSAGEM AS Mensagem,
        NEW_ID AS Id;
END