CREATE DEFINER=`root`@`localhost` PROCEDURE `SP_ACCESS_LEVEL_CREATE_OR_UPDATE`(
	IN P_ID INT,
	IN P_NAME VARCHAR(100),
    IN P_SECTORS_JSON JSON,
    IN P_ACCESS_SCHEDULE_ID INT
)
BEGIN
	DECLARE ERRO INT DEFAULT 0;
    DECLARE MENSAGEM VARCHAR(100) DEFAULT 'SUCESSO';
    DECLARE NEW_ID INT DEFAULT 0;

    DECLARE EXIT HANDLER FOR SQLEXCEPTION
	BEGIN
		ROLLBACK;

		SELECT 
			1 AS Erro,
			'ERRO AO INSERIR O CALENDÁRIO DE ACESSO' AS Mensagem,
			0 AS Id;
	END;
    
    START TRANSACTION;
    
    IF P_ID IS NULL OR P_ID = 0 THEN
		INSERT INTO ACCESS_LEVEL (NAME, ACCESS_SCHEDULE_ID)
        VALUES (P_NAME, P_ACCESS_SCHEDULE_ID);
        
        SET NEW_ID = LAST_INSERT_ID();
	ELSE
		UPDATE ACCESS_LEVEL
        SET 
			NAME = P_NAME,
			ACCESS_SCHEDULE_ID = P_ACCESS_SCHEDULE_ID
		WHERE ID = P_ID;
	END IF;
    
    DELETE FROM ACCESS_LEVEL_SECTOR
    WHERE ACCESS_LEVEL_ID = P_ID;
    
	INSERT INTO ACCESS_LEVEL_SECTOR (ACCESS_LEVEL_ID, SECTOR_ID, RULE_TYPE)
	SELECT P_ID, jt.sector_id, jt.rule_type
	FROM JSON_TABLE(
		P_SECTORS_JSON, 
		'$[*]' COLUMNS (
			sector_id INT PATH '$.SectorId',
            rule_type INT PATH '$.RuleType'
		)
	) jt;
    
    COMMIT;
    
    SELECT 
        ERRO AS Erro,
        MENSAGEM AS Mensagem,
        P_ID AS Id;
END