CREATE TABLE PERSON (
	ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(100),
    EMBEDDING JSON NOT NULL,
    IMAGE_PATH VARCHAR(255) NOT NULL,
    MAIN_SECTOR_ID INT NOT NULL,
    ACCESS_LEVEL_ID INT NOT NULL,
    ACTIVE TINYINT NOT NULL DEFAULT 1,
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    
    FOREIGN KEY (MAIN_SECTOR_ID) REFERENCES SECTOR(ID),
    FOREIGN KEY (ACCESS_LEVEL_ID) REFERENCES ACCESS_LEVEL(ID)
);

CREATE TABLE DEVICE (
	ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    TYPE ENUM('CAMERA', 'BIOMETRIC_SCANNER') NOT NULL,
    ORIGIN_SECTOR_ID INT NOT NULL,
    DESTINATION_SECTOR_ID INT,
    
    FOREIGN KEY (ORIGIN_SECTOR_ID) REFERENCES SECTOR(ID),
    FOREIGN KEY (DESTINATION_SECTOR_ID) REFERENCES SECTOR(ID)
);

CREATE TABLE CAMERA(
	ID INT AUTO_INCREMENT PRIMARY KEY,
    CONNECTION VARCHAR(255),
    DEVICE_ID INT,
    MAC_ADDRESS VARCHAR(100) NULL,
	CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    IS_ACTIVE TINYINT(1) NOT NULL DEFAULT 1,
    FOREIGN KEY (SECTOR_ID) REFERENCES SECTOR(ID),
    FOREIGN KEY (DEVICE_ID) REFERENCES DEVICE(ID)
);

CREATE TABLE ENVIRONMENT_MONITORING (
	ID INT AUTO_INCREMENT PRIMARY KEY,
    CAMERA_ID INT,
    PERSON_ID INT,
    SCORE DECIMAL(18,2),
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (CAMERA_ID) REFERENCES Camera(ID),
    FOREIGN KEY (PERSON_ID) REFERENCES Person(ID)
);

CREATE INDEX IDX_ENV_MON_PERSON_CREATED
ON ENVIRONMENT_MONITORING (PERSON_ID, CREATED_AT DESC);

CREATE TABLE INCIDENT_RECORDING (
	ID INT AUTO_INCREMENT PRIMARY KEY,
    CAMERA_ID INT NOT NULL,
    INCIDENT_TIME DATETIME NOT NULL,
    STATUS INT NOT NULL DEFAULT 1,
    FILE_NAME VARCHAR(300) NULL,
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATE_AT DATETIME NULL,
    FOREIGN KEY (CAMERA_ID) REFERENCES Camera(ID),
    FOREIGN KEY (PERSON_ID) REFERENCES Person(ID)
);

CREATE TABLE INCIDENT_RECORDING_PERSON (
	INCIDENT_RECORDING_ID INT,
    PERSON_ID INT,
    SEEN_AT DATETIME NOT NULL,
    VIDEO_OFFSET_SECONDS DECIMAL(10,3) NOT NULL,
    PRIMARY KEY (INCIDENT_RECORDING_ID, PERSON_ID),
    FOREIGN KEY (INCIDENT_RECORDING_ID) REFERENCES Incident_Recording(ID),
    FOREIGN KEY (PERSON_ID) REFERENCES Person(ID)
);

CREATE TABLE CAMERA_FEATURE (
	CAMERA_ID INT NOT NULL,
    FEATURE_ID INT NOT NULL,
    IS_ACTIVE TINYINT(1) NOT NULL DEFAULT 1,
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT DATETIME,
    PRIMARY KEY (CAMERA_ID, FEATURE_ID),
    FOREIGN KEY (CAMERA_ID) REFERENCES Camera(ID),
    FOREIGN KEY (FEATURE_ID) REFERENCES Feature(ID)
);

CREATE TABLE CAMERA_ROI (
	ID INT AUTO_INCREMENT PRIMARY KEY,
	CAMERA_ID INT NOT NULL,
    ROI_TYPE INT NOT NULL,
    COORDINATES_JSON JSON,
    IS_ACTIVE TINYINT(1) NOT NULL DEFAULT 1,
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    
    FOREIGN KEY (CAMERA_ID) REFERENCES Camera(ID)
);

CREATE TABLE NOTIFICATION_GROUP (
	ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(30) NOT NULL,
    IS_ACTIVE TINYINT(1) NOT NULL DEFAULT 1,
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE NOTIFICATION_GROUP_EMAIL (
	ID INT AUTO_INCREMENT PRIMARY KEY,
    EMAIL VARCHAR(100) NOT NULL,
    NOTIFICATION_GROUP_ID INT NOT NULL,
    FOREIGN KEY (NOTIFICATION_GROUP_ID) REFERENCES NOTIFICATION_GROUP(ID) ON DELETE CASCADE
);

CREATE TABLE SECTOR (
	ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    IS_ACTIVE TINYINT NOT NULL DEFAULT 1,
    PARENT_ID INT NULL,
    
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (PARENT_ID) REFERENCES SECTOR(ID)
);

CREATE TABLE SECTOR_NOTIFICATION_GROUP (
	SECTOR_ID INT NOT NULL,
    NOTIFICATION_GROUP_ID INT NOT NULL,
    PRIMARY KEY (SECTOR_ID, NOTIFICATION_GROUP_ID),
    FOREIGN KEY (SECTOR_ID) REFERENCES SECTOR(ID) ON DELETE CASCADE,
    FOREIGN KEY (NOTIFICATION_GROUP_ID) REFERENCES NOTIFICATION_GROUP(ID) ON DELETE CASCADE
);

CREATE TABLE ACCESS_SCHEDULE (
	ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    IS_ACTIVE TINYINT(1) NOT NULL DEFAULT 1,
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE ACCESS_SCHEDULE_RULE (
	ID INT AUTO_INCREMENT PRIMARY KEY,
    ACCESS_SCHEDULE_ID INT NOT NULL,
    WEEKDAY TINYINT NOT NULL,
    START_TIME TIME NOT NULL,
    END_TIME TIME NOT NULL,
    
	FOREIGN KEY (ACCESS_SCHEDULE_ID) REFERENCES ACCESS_SCHEDULE(ID)
    ON DELETE CASCADE
);

CREATE TABLE ACCESS_LEVEL (
	ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    ACCESS_SCHEDULE_ID INT NOT NULL,
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    
    FOREIGN KEY (ACCESS_SCHEDULE_ID) REFERENCES ACCESS_SCHEDULE(ID)
);

CREATE TABLE ACCESS_LEVEL_SECTOR (
	ACCESS_LEVEL_ID INT NOT NULL,
    SECTOR_ID INT NOT NULL,
    RULE_TYPE ENUM('WHITELIST', 'BLACKLIST') NOT NULL,
    
    PRIMARY KEY (ACCESS_LEVEL_ID, SECTOR_ID),
    FOREIGN KEY (ACCESS_LEVEL_ID) REFERENCES ACCESS_LEVEL(ID),
    FOREIGN KEY (SECTOR_ID) REFERENCES Sector(ID)
);

CREATE TABLE COMPLIANCE_POLICY (
	ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    TYPE ENUM('SECTOR_TRANSITION', 'EPI') NOT NULL,
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE COMPLIANCE_RULE_SECTOR_TRANSITION (
	ID INT AUTO_INCREMENT PRIMARY KEY,
    POLICY_ID INT NOT NULL,
    SECTOR_ID INT NOT NULL,
    ORDER_INDEX INT NOT NULL,
    MIN_TIME INT,
    MAX_TIME INT,
    FOREIGN KEY (SECTOR_ID) REFERENCES  Sector(ID),
    FOREIGN KEY (SECTOR_ID) REFERENCES  Sector(ID)
		ON DELETE CASCADE
);

CREATE TABLE COMPLIANCE_LOG (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    PERSON_ID INT NOT NULL,
    SECTOR_ID INT NOT NULL,
    EVENT_TYPE ENUM('ENTRY', 'EXIT') NOT NULL,
    ENTERED_AT DATETIME NOT NULL,
    ENTERED_AT DATETIME,
    FOREIGN KEY (PERSON_ID) REFERENCES Person(ID),
    FOREIGN KEY (SECTOR_ID) REFERENCES Sector(ID)
);


CREATE TABLE COMPLIANCE_VIOLATIONS (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    LOG_ID INT,
    POLICY_ID INT,
    PERSON_ID INT,
    VIOLATION_TYPE VARCHAR(50),
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (LOG_ID) REFERENCES COMPLIANCE_LOG(ID),
    FOREIGN KEY (PERSON_ID) REFERENCES PERSON(ID),
    FOREIGN KEY (POLICY_ID) REFERENCES COMPLIANCE_POLICY(ID)
);


	