CREATE TABLE PERSON (
	ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(100),
    EMBEDDING JSON NOT NULL,
    IMAGE_PATH VARCHAR(255) NOT NULL,
    ACTIVE TINYINT NOT NULL DEFAULT 1,
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE SECTOR (
	ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    ACTIVE TINYINT NOT NULL DEFAULT 1,
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE CAMERA (
	ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    CONNECTION VARCHAR(255),
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    SECTOR_ID INT,
    FOREIGN KEY (SECTOR_ID) REFERENCES SECTOR(ID)
		ON DELETE CASCADE
        ON UPDATE CASCADE
);

CREATE TABLE PERSON_SECTOR (
    PERSON_ID INT NOT NULL,
    SECTOR_ID INT NOT NULL,
    PRIMARY KEY (PERSON_ID, SECTOR_ID),
    FOREIGN KEY (PERSON_ID) REFERENCES Person(ID),
    FOREIGN KEY (SECTOR_ID) REFERENCES Sector(ID)
);

CREATE TABLE ENVIRONMENT_MONITORING_LOG (
	ID INT AUTO_INCREMENT PRIMARY KEY,
    CAMERA_ID INT,
    PERSON_ID INT,
    SCORE DECIMAL(18,2),
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (CAMERA_ID) REFERENCES Camera(ID),
    FOREIGN KEY (PERSON_ID) REFERENCES Person(ID)
);

CREATE TABLE INCIDENT_RECORDING_LOG (
	ID INT AUTO_INCREMENT PRIMARY KEY,
    CAMERA_ID INT NOT NULL,
    PERSON_ID INT NULL,
    INCIDENT_TIME DATETIME NOT NULL,
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (CAMERA_ID) REFERENCES Camera(ID),
    FOREIGN KEY (PERSON_ID) REFERENCES Person(ID)
)

	