CREATE TABLE PERSON (
	ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(100),
    EMBEDDING JSON NOT NULL,
    IMAGE_PATH VARCHAR(255) NOT NULL,
    ACTIVE TINYINT NOT NULL DEFAULT 1,
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE CAMERA (
	ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    CONNECTION VARCHAR(255),
    SECTOR_ID INT,
    MAC_ADDRESS VARCHAR(100) NULL,
	CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT DATETIME,
    IS_ACTIVE TINYINT(1) NOT NULL DEFAULT 1,
    FOREIGN KEY (SECTOR_ID) REFERENCES SECTOR(ID)
		ON DELETE CASCADE
        ON UPDATE CASCADE
);

CREATE TABLE PERSON_SECTOR (
    PERSON_ID INT NOT NULL,
    SECTOR_ID INT NOT NULL,
    PRIMARY KEY (PERSON_ID, SECTOR_ID),
    FOREIGN KEY (PERSON_ID) REFERENCES Person(ID),
    FOREIGN KEY (SECTOR_ID) REFERENCES Sector(ID)
);

CREATE TABLE ENVIRONMENT_MONITORING (
	ID INT AUTO_INCREMENT PRIMARY KEY,
    CAMERA_ID INT,
    PERSON_ID INT,
    SCORE DECIMAL(18,2),
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (CAMERA_ID) REFERENCES Camera(ID),
    FOREIGN KEY (PERSON_ID) REFERENCES Person(ID)
);

CREATE INDEX IDX_ENV_MON_PERSON_CREATED
ON ENVIRONMENT_MONITORING (PERSON_ID, CREATED_AT DESC);

CREATE TABLE INCIDENT_RECORDING (
	ID INT AUTO_INCREMENT PRIMARY KEY,
    CAMERA_ID INT NOT NULL,
    INCIDENT_TIME DATETIME NOT NULL,
    STATUS INT NOT NULL DEFAULT 1,
    FILE_NAME VARCHAR(300) NULL,
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATE_AT DATETIME NULL,
    FOREIGN KEY (CAMERA_ID) REFERENCES Camera(ID),
    FOREIGN KEY (PERSON_ID) REFERENCES Person(ID)
);

CREATE TABLE INCIDENT_RECORDING_PERSON (
	INCIDENT_RECORDING_ID INT,
    PERSON_ID INT,
    SEEN_AT DATETIME NOT NULL,
    VIDEO_OFFSET_SECONDS DECIMAL(10,3) NOT NULL,
    PRIMARY KEY (INCIDENT_RECORDING_ID, PERSON_ID),
    FOREIGN KEY (INCIDENT_RECORDING_ID) REFERENCES Incident_Recording(ID),
    FOREIGN KEY (PERSON_ID) REFERENCES Person(ID)
);

CREATE TABLE DWELL_TIME_MONITORING (
	ID INT AUTO_INCREMENT PRIMARY KEY,
    CAMERA_ID INT NOT NULL,
    PERSON_ID INT NOT NULL,
    ENTERED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    EXISTED_AT DATETIME NOT NULL,
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATE_AT DATETIME NULL,
    FOREIGN KEY (CAMERA_ID) REFERENCES Camera(ID),
    FOREIGN KEY (PERSON_ID) REFERENCES Person(ID)
);

CREATE TABLE FEATURE (
	ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    DESCRIPTION VARCHAR(500) NOT NULL,
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO FEATURE (NAME, DESCRIPTION)
VALUES ("Controle de ambientes", "Realiza monitoramento dos ambientes registrando os setores onde a pessoa se encontra");

INSERT INTO FEATURE (NAME, DESCRIPTION)
VALUES ("Captura de incidentes", "Captura o vídeo e realiza o reconhecimento da pessoa no momento em que um disparo de alerta é acionado");

INSERT INTO FEATURE (NAME, DESCRIPTION)
VALUES ("Controle de permanencia", "Realiza o controle de uma pessoa em um ambiente com base em um tempo pré definido");

CREATE TABLE CAMERA_FEATURE (
	CAMERA_ID INT NOT NULL,
    FEATURE_ID INT NOT NULL,
    IS_ACTIVE TINYINT(1) NOT NULL DEFAULT 1,
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT DATETIME,
    PRIMARY KEY (CAMERA_ID, FEATURE_ID),
    FOREIGN KEY (CAMERA_ID) REFERENCES Camera(ID),
    FOREIGN KEY (FEATURE_ID) REFERENCES Feature(ID)
);

CREATE TABLE NOTIFICATION_GROUP (
	ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(30) NOT NULL,
    IS_ACTIVE TINYINT(1) NOT NULL DEFAULT 1,
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT DATETIME
);

CREATE TABLE NOTIFICATION_GROUP_EMAIL (
	ID INT AUTO_INCREMENT PRIMARY KEY,
    EMAIL VARCHAR(100) NOT NULL,
    NOTIFICATION_GROUP_ID INT NOT NULL,
    FOREIGN KEY (NOTIFICATION_GROUP_ID) REFERENCES NOTIFICATION_GROUP(ID) ON DELETE CASCADE
);

CREATE TABLE SECTOR (
	ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    ACTIVE TINYINT NOT NULL DEFAULT 1,
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE SECTOR_NOTIFICATION_GROUP (
	SECTOR_ID INT NOT NULL,
    NOTIFICATION_GROUP_ID INT NOT NULL,
    PRIMARY KEY (SECTOR_ID, NOTIFICATION_GROUP_ID),
    FOREIGN KEY (SECTOR_ID) REFERENCES SECTOR(ID) ON DELETE CASCADE,
    FOREIGN KEY (NOTIFICATION_GROUP_ID) REFERENCES NOTIFICATION_GROUP(ID) ON DELETE CASCADE
);
 
	