CREATE DEFINER=`root`@`localhost` PROCEDURE `SP_CAMERA_GET_ENVIRONMENT_MONITORING_LOG`(
	IN P_CAMERA_ID INT
)
BEGIN
	SELECT
		P.NAME AS Person,
		S.NAME AS Sector,
        L.CREATED_AT
    FROM ENVIRONMENT_MONITORING L
    LEFT JOIN PERSON P ON P.ID = L.PERSON_ID
    LEFT JOIN CAMERA C ON C.ID = P_CAMERA_ID
    LEFT JOIN SECTOR S ON S.ID = C.SECTOR_ID
	WHERE L.CAMERA_ID = P_CAMERA_ID;
END