CREATE DEFINER=`root`@`localhost` PROCEDURE `SP_CAMERA_GET_FEATURES_BY_CAMERA_ID`(
	IN P_CAMERA_ID INT
)
BEGIN
	SELECT
		CF.FEATURE_ID
	FROM CAMERA_FEATURE CF
    WHERE CF.CAMERA_ID = P_CAMERA_ID AND CF.IS_ACTIVE = 1;
END