CREATE DEFINER=`root`@`localhost` PROCEDURE `SP_CAMERA_UPDATE`(
	IN P_CAMERA_ID INT,
    IN P_NAME VARCHAR(100),
    IN P_CONNECTION VARCHAR(255),
    IN P_SECTOR_ID INT,
    IN P_FEATURES_JSON JSON
)
BEGIN
    DECLARE ERRO INT DEFAULT 0;
    DECLARE MENSAGEM VARCHAR(100) DEFAULT 'SUCESSO';

    DECLARE EXIT HANDLER FOR SQLEXCEPTION
	BEGIN
		ROLLBACK;

		SELECT 
			1 AS Erro,
			'ERRO AO INSERIR CAMERA' AS Mensagem,
			0 AS Id;
	END;

    START TRANSACTION;

        UPDATE CAMERA
        SET
			NAME = P_NAME,
            CONNECTION = P_CONNECTION,
            SECTOR_ID = P_SECTOR_ID,
            UPDATED_AT = NOW()
		WHERE ID = P_CAMERA_ID;

		INSERT INTO CAMERA_FEATURE (CAMERA_ID, FEATURE_ID)
		SELECT 
			P_CAMERA_ID,
			jt.FEATURE_ID
		FROM JSON_TABLE(
			P_FEATURES_JSON,
			'$[*]' COLUMNS (
				FEATURE_ID INT PATH '$'
			)
		) jt
		LEFT JOIN CAMERA_FEATURE cf
			ON cf.CAMERA_ID = P_CAMERA_ID
		   AND cf.FEATURE_ID = jt.FEATURE_ID
		WHERE cf.FEATURE_ID IS NULL;


        UPDATE CAMERA_FEATURE cf
		JOIN JSON_TABLE(
			P_FEATURES_JSON,
			'$[*]' COLUMNS (
				FEATURE_ID INT PATH '$'
			)
		) jt
		  ON jt.FEATURE_ID = cf.FEATURE_ID
		SET 
			cf.IS_ACTIVE = 1,
            cf.UPDATED_AT = NOW()
		WHERE cf.CAMERA_ID = P_CAMERA_ID;
        
        UPDATE CAMERA_FEATURE cf
		LEFT JOIN JSON_TABLE(
			P_FEATURES_JSON,
			'$[*]' COLUMNS (
				FEATURE_ID INT PATH '$'
			)
		) jt
		  ON jt.FEATURE_ID = cf.FEATURE_ID
		SET 
			cf.IS_ACTIVE = 0,
            cf.UPDATED_AT = NOW()
		WHERE cf.CAMERA_ID = P_CAMERA_ID
		  AND jt.FEATURE_ID IS NULL;

    COMMIT;

    SELECT 
        ERRO AS Erro,
        MENSAGEM AS Mensagem,
        NEW_ID AS Id;
END