CREATE DEFINER=`root`@`localhost` PROCEDURE `SP_CAMERA_GET_BY_FEATURE_ID`(
	IN P_FEATURE_ID INT
)
BEGIN
	SELECT
		C.ID,
		C.NAME,
		C.CONNECTION,
		C.SECTOR_ID AS SectorId,
		S.NAME AS SectorName
	FROM CAMERA C
    LEFT JOIN SECTOR S ON S.ID = C.SECTOR_ID
    LEFT JOIN CAMERA_FEATURE CF ON CF.CAMERA_ID = C.ID
    WHERE CF.FEATURE_ID = P_FEATURE_ID;
END