CREATE DEFINER=`root`@`localhost` PROCEDURE `SP_DWELL_TIME_MONITORING_GET_BY_CAMERA_ID`(
	IN P_CAMERA_ID INT
)
BEGIN
	SELECT
		P.NAME AS PersonName,
        P.IMAGE_PATH AS ImagePath,
		DTM.FIRST_SEEN AS FirstSeen,
        DTM.LAST_SEEN AS LastSeen
	FROM DWELL_TIME_MONITORING DTM
    LEFT JOIN PERSON P ON P.ID = DTM.PERSON_ID
    WHERE DTM.CAMERA_ID = P_CAMERA_ID;
END