CREATE DEFINER=`root`@`localhost` PROCEDURE `SP_DWELL_TIME_MONITORING_CREATE`(
    IN P_CAMERA_ID INT,
    IN P_PERSON_ID INT
)
BEGIN
	DECLARE ERRO INT DEFAULT 0;
    DECLARE MENSAGEM VARCHAR(100) DEFAULT 'SUCESSO';
    DECLARE NEW_ID INT DEFAULT 0;

    DECLARE EXIT HANDLER FOR SQLEXCEPTION
    BEGIN
        SET ERRO = 1;
        SET MENSAGEM = 'ERRO AO CRIAR LOG';
        ROLLBACK;
    END;

    START TRANSACTION;
		INSERT INTO DWELL_TIME_MONITORING (CAMERA_ID, PERSON_ID)
		VALUES (P_CAMERA_ID, P_PERSON_ID);
		
		SET NEW_ID = LAST_INSERT_ID();
	COMMIT;
    
    SELECT 
        ERRO AS Erro,
        MENSAGEM AS Mensagem,
        NEW_ID AS Id;
END