CREATE DEFINER=`root`@`localhost` PROCEDURE `SP_DWELL_TIME_MONITORING_UPDATE`(
	IN P_ID INT
)
BEGIN
	DECLARE ERRO INT DEFAULT 0;
    DECLARE MENSAGEM VARCHAR(100) DEFAULT "SUCESSO";
    
    DECLARE EXIT HANDLER FOR SQLEXCEPTION
    BEGIN
		ROLLBACK;
        
        SELECT
			1 AS ERRO,
            "ERRO AO ATUALIZAR CONTROLE DE PERMANENCIA" AS Mensagem,
            0 AS Id;
	END;
    
    START TRANSACTION;
    
		UPDATE DWELL_TIME_MONITORING
        SET
			LAST_SEEN = CURRENT_TIMESTAMP,
            UPDATE_AT = CURRENT_TIMESTAMP
		WHERE ID = P_ID;
        
	COMMIT;
			
	SELECT 
		ERRO,
		MENSAGEM,
		P_ID AS Id;
END