CREATE DEFINER=`root`@`localhost` PROCEDURE `SP_DWELL_TIME_MONITORING_GET_ALL`()
BEGIN
	SELECT
		P.ID AS PersonId,
		P.NAME AS PersonName,
        C.ID AS CameraId,
        C.NAME AS CameraName,
		FIRST_SEEN AS FirstSeen,
        LAST_SEEN AS LastSeen
	FROM DWELL_TIME_MONITORING DTM
    LEFT JOIN PERSON P ON P.ID = DTM.PERSON_ID
    LEFT JOIN CAMERA C ON C.ID = DTM.CAMERA_ID;
END