CREATE DEFINER=`root`@`localhost` PROCEDURE `SP_INCIDENT_RECORDING_GET_TO_PROCESS`()
BEGIN
	SELECT
		IR.ID,
		IR.CAMERA_ID AS CameraId,
        IR.INCIDENT_TIME AS IncidentTime
	FROM INCIDENT_RECORDING_LOG IR
    WHERE IR.STATUS = 1
    LIMIT 1;
END