CREATE DEFINER=`root`@`localhost` PROCEDURE `SP_INCIDENT_RECORDING_UPDATE_LOG`(
    IN P_LOG_ID INT,
    IN P_PERSON_IDS_JSON JSON,
    IN P_VIDEO_PATH VARCHAR(300)
)
BEGIN
    DECLARE ERRO INT DEFAULT 0;
    DECLARE MENSAGEM VARCHAR(100) DEFAULT 'SUCESSO';

    DECLARE EXIT HANDLER FOR SQLEXCEPTION
	BEGIN
		ROLLBACK;

		SELECT 
			1 AS Erro,
			'ERRO AO INSERIR CAMERA' AS Mensagem,
			0 AS Id;
	END;

    START TRANSACTION;

        UPDATE INCIDENT_RECORDING_LOG
        SET 
			STATUS = 3,
            VIDEO_PATH = P_VIDEO_PATH, 
            UPDATE_AT = NOW()
        WHERE ID = P_LOG_ID;

		INSERT INTO INCIDENT_RECORDING_LOG_PERSON (INCIDENT_RECORDING_LOG_ID, PERSON_ID)
        SELECT P_LOG_ID, jt.id
		FROM JSON_TABLE(P_PERSON_IDS_JSON, '$[*]' COLUMNS (id INT PATH '$')) jt;

    COMMIT;

    SELECT 
        ERRO AS Erro,
        MENSAGEM AS Mensagem,
        P_LOG_ID AS Id;
END