CREATE DEFINER=`root`@`localhost` PROCEDURE `SP_INCIDENT_RECORDING_GET_LOG_BY_ID`(
	IN P_LOG_ID INT
)
BEGIN
	SELECT
		IR.ID,
		S.NAME AS Sector,
        IR.INCIDENT_TIME AS IncidentTime,
        IR.STATUS,
        IR.FILE_NAME AS FileName,
        IR.CREATED_AT,
        CASE 
			WHEN COUNT(IRP.INCIDENT_RECORDING_LOG_ID) = 0 THEN NULL
				ELSE JSON_ARRAYAGG(
					JSON_OBJECT(
						"Id", P.ID,
						"Name", P.NAME,
						"ImagePath", P.IMAGE_PATH,
						"SeenAt", DATE_FORMAT(IRP.SEEN_AT, '%Y-%m-%dT%H:%i:%s.%fZ'),
                        "VideoOffsetSeconds", IRP.VIDEO_OFFSET_SECONDS
					)
				) 
			END AS PERSONSJSON
    FROM INCIDENT_RECORDING_LOG IR
    LEFT JOIN CAMERA C ON C.ID = IR.CAMERA_ID
    LEFT JOIN SECTOR S ON S.ID = C.SECTOR_ID
    LEFT JOIN INCIDENT_RECORDING_LOG_PERSON IRP ON IRP.INCIDENT_RECORDING_LOG_ID = IR.ID
    LEFT JOIN PERSON P ON P.ID = IRP.PERSON_ID
    WHERE IR.ID = P_LOG_ID
    GROUP BY
		IR.ID,
		S.NAME,
        IR.INCIDENT_TIME,
        IR.STATUS,
        IR.FILE_NAME,
        IR.CREATED_AT
    ORDER BY 
		IR.CREATED_AT;
END