CREATE DEFINER=`root`@`localhost` PROCEDURE `SP_INCIDENT_RECORDING_CREATE_LOG`(
    IN P_MAC_ADDRESS VARCHAR(100),
    IN P_INCIDENT_TIME DATETIME
)
BEGIN
	DECLARE ERRO INT DEFAULT 0;
    DECLARE MENSAGEM VARCHAR(100) DEFAULT 'SUCESSO';
    DECLARE NEW_ID INT DEFAULT 0;
    DECLARE V_CAMERA_ID INT;

    DECLARE EXIT HANDLER FOR SQLEXCEPTION
    BEGIN
        SET ERRO = 1;
        SET MENSAGEM = 'ERRO AO CRIAR LOG';
        ROLLBACK;
    END;

    START TRANSACTION;
		
        SELECT ID
        INTO V_CAMERA_ID
        FROM CAMERA
        WHERE MAC_ADDRESS = P_MAC_ADDRESS
        LIMIT 1;
        
        IF V_CAMERA_ID IS NULL THEN
			SET ERRO = 1;
            SET MENSAGEM = "CAMERA NÃO ENCONTRADA PARA O MAC ADDRESS INFORMADO";
            ROLLBACK;
		ELSE
			INSERT INTO INCIDENT_RECORDING_LOG (CAMERA_ID, INCIDENT_TIME)
			VALUES (V_CAMERA_ID, P_INCIDENT_TIME);
            
			SET NEW_ID = LAST_INSERT_ID();
			COMMIT;
		END IF;

    SELECT 
        ERRO AS Erro,
        MENSAGEM AS Mensagem,
        NEW_ID AS Id;
END