CREATE DEFINER=`root`@`localhost` PROCEDURE `SP_INCIDENT_RECORDING_CREATE_LOG`(
    IN P_CAMERA_ID INT,
    IN P_INCIDENT_TIME DATETIME
)
BEGIN
	DECLARE ERRO INT DEFAULT 0;
    DECLARE MENSAGEM VARCHAR(100) DEFAULT 'SUCESSO';
    DECLARE NEW_ID INT DEFAULT 0;

    DECLARE EXIT HANDLER FOR SQLEXCEPTION
    BEGIN
        SET ERRO = 1;
        SET MENSAGEM = 'ERRO AO CRIAR LOG';
        ROLLBACK;
    END;

    START TRANSACTION;

        INSERT INTO INCIDENT_RECORDING_LOG (CAMERA_ID, INCIDENT_TIME)
        VALUES (P_CAMERA_ID, P_INCIDENT_TIME);

        SET NEW_ID = LAST_INSERT_ID();

    COMMIT;

    SELECT 
        ERRO AS Erro,
        MENSAGEM AS Mensagem,
        NEW_ID AS Id;
END