CREATE DEFINER=`root`@`localhost` PROCEDURE `SP_INCIDENT_RECORDING_GET_TO_PROCESS`()
BEGIN
	DECLARE V_ID INT;
    
    START TRANSACTION;
	
	SELECT IR.ID
	INTO V_ID
	FROM INCIDENT_RECORDING_LOG IR
	WHERE IR.STATUS = 1
	ORDER BY IR.INCIDENT_TIME
	LIMIT 1
	FOR UPDATE;
	
	IF V_ID IS NULL THEN
		ROLLBACK;
		SELECT NULL AS ID;
	ELSE
		UPDATE INCIDENT_RECORDING_LOG
		SET STATUS = 2,
			UPDATE_AT = NOW()
		WHERE ID = V_ID;
		
		COMMIT;

		SELECT
			IR.ID,
			IR.CAMERA_ID AS CameraId,
			IR.INCIDENT_TIME AS IncidentTime
		FROM INCIDENT_RECORDING_LOG IR
		WHERE IR.ID = V_ID
		LIMIT 1;
    
    END IF;
END