CREATE DEFINER=`root`@`localhost` PROCEDURE `SP_PERSON_CREATE`(
    IN P_NAME VARCHAR(100),
    IN P_EMBEDDING JSON,
    IN P_IMAGE_PATH VARCHAR(255),
    IN P_SECTORS_ID_JSON JSON
)
BEGIN
    DECLARE ERRO INT DEFAULT 0;
    DECLARE MENSAGEM VARCHAR(100) DEFAULT 'SUCESSO';
    DECLARE NEW_ID INT DEFAULT 0;

    DECLARE EXIT HANDLER FOR SQLEXCEPTION
    BEGIN
        SET ERRO = 1;
        SET MENSAGEM = 'ERRO AO INSERIR PESSOA';
        ROLLBACK;
        
		SELECT 
            ERRO AS Erro,
            MENSAGEM AS Mensagem,
            0 AS Id;
    END;

    START TRANSACTION;

        INSERT INTO person (NAME, EMBEDDING, IMAGE_PATH)
        VALUES (P_NAME, P_EMBEDDING, P_IMAGE_PATH);

        SET NEW_ID = LAST_INSERT_ID();
        
        INSERT INTO PERSON_SECTOR (PERSON_ID, SECTOR_ID)
        SELECT NEW_ID, jt.id
		FROM JSON_TABLE(P_SECTORS_ID_JSON, '$[*]' COLUMNS (id INT PATH '$')) jt;
        
    COMMIT;

    SELECT 
        ERRO AS Erro,
        MENSAGEM AS Mensagem,
        NEW_ID AS Id;
END