CREATE DEFINER=`root`@`localhost` PROCEDURE `SP_PERSON_GET_ENVIRONMENT_MONITORING_LOG_BY_ID`(
	IN P_PERSON_ID INT
)
BEGIN
	SELECT
		S.NAME AS Sector,
        L.CREATED_AT
    FROM ENVIRONMENT_MONITORING L
    LEFT JOIN CAMERA C ON C.ID = L.CAMERA_ID
    LEFT JOIN SECTOR S ON S.ID = C.SECTOR_ID
	WHERE L.PERSON_ID = P_PERSON_ID;
END