CREATE DEFINER=`root`@`localhost` PROCEDURE `SP_PERSON_GET_ALL_ENVIRONMENT_MONITORING_LOG`()
BEGIN
	SELECT
		S.NAME AS Sector,
        L.CREATED_AT
    FROM ENVIRONMENT_MONITORING_LOG L
    LEFT JOIN CAMERA C ON C.ID = L.CAMERA_ID
    LEFT JOIN SECTOR S ON S.ID = C.SECTOR_ID
    ORDER BY L.CREATED_AT;
END