CREATE DEFINER=`root`@`localhost` PROCEDURE `SP_ACCESS_SCHEDULE_CREATE_OR_UPDATE`(
	IN P_ID INT,
	IN P_NAME VARCHAR(100),
    IN P_IS_ACTIVE TINYINT(1),
    IN P_RULES_JSON JSON
)
BEGIN
	DECLARE ERRO INT DEFAULT 0;
    DECLARE MENSAGEM VARCHAR(100) DEFAULT 'SUCESSO';
    DECLARE NEW_ID INT DEFAULT 0;

    DECLARE EXIT HANDLER FOR SQLEXCEPTION
	BEGIN
		ROLLBACK;

		SELECT 
			1 AS Erro,
			'ERRO AO INSERIR O CALENDÁRIO DE ACESSO' AS Mensagem,
			0 AS Id;
	END;
    
    START TRANSACTION;
	
    IF P_ID IS NULL OR P_ID = 0 THEN
        INSERT INTO ACCESS_SCHEDULE (NAME, IS_ACTIVE)
        VALUES (P_NAME, P_IS_ACTIVE);

        SET P_ID = LAST_INSERT_ID();
	ELSE
		UPDATE ACCESS_SCHEDULE
        SET 
			NAME = P_NAME,
			IS_ACTIVE = P_IS_ACTIVE
		WHERE ID = P_ID;
	END IF;
    
    DELETE FROM ACCESS_SCHEDULE_RULES
    WHERE ACCESS_SCHEDULE_ID = P_ID;

	INSERT INTO ACCESS_SCHEDULE_RULES (ACCESS_SCHEDULE_ID, WEEKDAY, START_TIME, END_TIME)
	SELECT P_ID, jt.weekday, jt.start_time, jt.end_time
	FROM JSON_TABLE(
		P_RULES_JSON, 
		'$[*]' COLUMNS (
			weekday int PATH '$.WeekDay',
			start_time TIME PATH '$.StartTime',
			end_time TIME PATH '$.EndTime'
		)
	) jt;

    COMMIT;
    
    SELECT 
        ERRO AS Erro,
        MENSAGEM AS Mensagem,
        P_ID AS Id;
    
END