CREATE DEFINER=`root`@`localhost` PROCEDURE `SP_SECTOR_CREATE`(
    IN P_NAME VARCHAR(100),
    IN P_PARENT_ID INT,
    IN P_NOTIFICATION_GROUP_JSON JSON
)
BEGIN
    DECLARE ERRO INT DEFAULT 0;
    DECLARE MENSAGEM VARCHAR(100) DEFAULT 'SUCESSO';
    DECLARE NEW_ID INT DEFAULT 0;

    DECLARE EXIT HANDLER FOR SQLEXCEPTION
    BEGIN
        SET ERRO = 1;
        SET MENSAGEM = 'ERRO AO INSERIR O SETOR';
        ROLLBACK;
    END;

    START TRANSACTION;

        INSERT INTO sector (NAME, PARENT_ID)
        VALUES (P_NAME, P_PARENT_ID);

        SET NEW_ID = LAST_INSERT_ID();
        
        INSERT INTO SECTOR_NOTIFICATION_GROUP (SECTOR_ID, NOTIFICATION_GROUP_ID)
        SELECT NEW_ID, jt.notification_group_id
        FROM JSON_TABLE(P_NOTIFICATION_GROUP_JSON, '$[*]' COLUMNS (notification_group_id INT PATH '$')) jt;
        
    COMMIT;

    SELECT 
        ERRO AS Erro,
        MENSAGEM AS Mensagem,
        NEW_ID AS Id;
END