CREATE DEFINER=`root`@`localhost` PROCEDURE `SP_ENVIRONMENT_MONITORING_GET_LAST_REGISTER_PER_PERSON`()
BEGIN
	SELECT
		P.ID AS PersonId,
		P.NAME AS Person,
        P.IMAGE_PATH AS PersonPhoto,
        IFNULL(S.ID, 0) AS SectorId,
		IFNULL(S.NAME, "Fora da empresa") AS Sector,
        EM.CREATED_AT
	FROM PERSON P
	LEFT JOIN ENVIRONMENT_MONITORING EM
		ON EM.ID = (
			SELECT EM2.ID
			FROM ENVIRONMENT_MONITORING EM2
			WHERE EM2.PERSON_ID = P.ID AND EM2.CREATED_AT >= CURDATE() AND EM2.CREATED_AT < CURDATE() + INTERVAL 1 DAY
			ORDER BY EM2.CREATED_AT DESC
			LIMIT 1
		)
	LEFT JOIN CAMERA C ON C.ID = EM.CAMERA_ID
	LEFT JOIN SECTOR S ON S.ID = C.SECTOR_ID;
END