CREATE DEFINER=`root`@`localhost` PROCEDURE `SP_ENVIRONMENT_MONITORING_GET_BY_ID`(
	IN P_LOG_ID INT
)
BEGIN
	SELECT
		P.ID AS PersonId,
		P.NAME AS Person,
        P.IMAGE_PATH AS PersonPhoto,
        S.ID AS SectorId,
		S.NAME AS Sector,
        L.IDENTIFIED_AT
    FROM ENVIRONMENT_MONITORING L
    LEFT JOIN DEVICE D ON D.ID = L.DEVICE_ID
    LEFT JOIN SECTOR S ON S.ID = C.SECTOR_ID
    LEFT JOIN PERSON P ON P.ID = L.PERSON_ID
    WHERE L.ID = P_LOG_ID
    ORDER BY L.IDENTIFIED_AT;
END