CREATE DEFINER=`root`@`localhost` PROCEDURE `SP_ENVIRONMENT_MONITORING_GET_ALL_LOGS`(
	IN P_PAGE_NUMBER INT,
    IN P_PAGE_SIZE INT
)
BEGIN
	DECLARE V_OFFSET_VALUE INT;
    SET V_OFFSET_VALUE  = (P_PAGE_NUMBER - 1) * P_PAGE_SIZE;

	SELECT
		P.ID AS PersonId,
		P.NAME AS Person,
        P.IMAGE_PATH AS PersonPhoto,
        S.ID AS SectorId,
		S.NAME AS Sector,
        L.IDENTIFIED_AT
    FROM ENVIRONMENT_MONITORING L
    LEFT JOIN CAMERA C ON C.ID = L.CAMERA_ID
    LEFT JOIN SECTOR S ON S.ID = C.SECTOR_ID
    LEFT JOIN PERSON P ON P.ID = L.PERSON_ID
    ORDER BY L.CREATED_AT DESC
    LIMIT P_PAGE_SIZE OFFSET V_OFFSET_VALUE;
END