CREATE DEFINER=`root`@`localhost` PROCEDURE `SP_ENVIRONMENT_MONITORING_CREATE_LOG`(
    IN P_DEVICE_ID INT,
    IN P_PERSON_ID INT,
    IN P_SCORE DECIMAL(18,2),
    IN P_IDENTIFIED_AT DATETIME
)
BEGIN
	DECLARE ERRO INT DEFAULT 0;
    DECLARE MENSAGEM VARCHAR(100) DEFAULT 'SUCESSO';
    DECLARE NEW_ID INT DEFAULT 0;

    DECLARE EXIT HANDLER FOR SQLEXCEPTION
    BEGIN
        SET ERRO = 1;
        SET MENSAGEM = 'ERRO AO CRIAR LOG';
        ROLLBACK;
    END;

    START TRANSACTION;

        INSERT INTO ENVIRONMENT_MONITORING (DEVICE_ID, PERSON_ID, IDENTIFIED_AT, SCORE)
        VALUES (P_DEVICE_ID, P_PERSON_ID, P_IDENTIFIED_AT, P_SCORE);

        SET NEW_ID = LAST_INSERT_ID();

    COMMIT;

    SELECT 
        ERRO AS Erro,
        MENSAGEM AS Mensagem,
        NEW_ID AS Id;
END