CREATE DEFINER=`root`@`localhost` PROCEDURE `SP_ENVIRONMENT_MONITORING_GET_ALL_LOGS`()
BEGIN
	SELECT
		P.NAME AS Person,
        P.IMAGE_PATH AS PersonPhoto,
        S.ID AS SectorId,
		S.NAME AS Sector,
        L.CREATED_AT
    FROM ENVIRONMENT_MONITORING L
    LEFT JOIN CAMERA C ON C.ID = L.CAMERA_ID
    LEFT JOIN SECTOR S ON S.ID = C.SECTOR_ID
    LEFT JOIN PERSON P ON P.ID = L.PERSON_ID
    ORDER BY L.CREATED_AT;
END