CREATE DEFINER=`root`@`localhost` PROCEDURE `SP_PERSON_CREATE`(
    IN P_NAME VARCHAR(100),
    IN P_MAIN_SECTOR_ID INT,
    IN P_ACCESS_LEVEL_ID INT
)
BEGIN
    DECLARE ERRO INT DEFAULT 0;
    DECLARE MENSAGEM VARCHAR(100) DEFAULT 'SUCESSO';
    DECLARE NEW_ID INT DEFAULT 0;

    DECLARE EXIT HANDLER FOR SQLEXCEPTION
    BEGIN
        SET ERRO = 1;
        SET MENSAGEM = 'ERRO AO INSERIR PESSOA';
        ROLLBACK;
        
		SELECT 
            ERRO AS Erro,
            MENSAGEM AS Mensagem,
            0 AS Id;
    END;

    START TRANSACTION;

        INSERT INTO person (NAME, MAIN_SECTOR_ID, ACCESS_LEVEL_ID)
        VALUES (P_NAME, P_MAIN_SECTOR_ID, P_ACCESS_LEVEL_ID);

        SET NEW_ID = LAST_INSERT_ID();

    COMMIT;

    SELECT 
        Erro AS Erro,
        MENSAGEM AS Mensagem,
        NEW_ID AS Id;
END