CREATE DEFINER=`root`@`localhost` PROCEDURE `SP_PERSON_CREATE_RECOGNIZE`(
	IN P_PERSON_ID INT,
	IN P_IMAGE_PATH VARCHAR(255),
    IN P_EMBEDDING JSON
)
BEGIN
    DECLARE ERRO INT DEFAULT 0;
    DECLARE MENSAGEM VARCHAR(100) DEFAULT 'SUCESSO';
    DECLARE NEW_ID INT DEFAULT 0;

    DECLARE EXIT HANDLER FOR SQLEXCEPTION
    BEGIN
        SET ERRO = 1;
        SET MENSAGEM = 'ERRO AO INSERIR PESSOA';
        ROLLBACK;
        
		SELECT 
            ERRO AS Erro,
            MENSAGEM AS Mensagem,
            0 AS Id;
    END;

    START TRANSACTION;

        UPDATE person 
        SET
			IMAGE_PATH = P_IMAGE_PATH,
			EMBEDDING = P_EMBEDDING
		WHERE ID = P_PERSON_ID;
        
    COMMIT;

    SELECT 
        Erro AS Erro,
        MENSAGEM AS Mensagem,
        NEW_ID AS Id;
END