CREATE DEFINER=`root`@`localhost` PROCEDURE `SP_PERSON_GET_ALL_CACHE`()
BEGIN
    SELECT
		P.ID,
		P.EMBEDDINGNEW AS EMBEDDING,
        P.ACCESS_LEVEL_ID,
		EM.CAMERA_ID,
		EM.CREATED_AT
	FROM PERSON P
	LEFT JOIN ENVIRONMENT_MONITORING EM 
		ON EM.ID = (
			SELECT MAX(EM2.ID)
			FROM ENVIRONMENT_MONITORING EM2
			WHERE EM2.PERSON_ID = P.ID
		)
	WHERE P.ACTIVE = 1;
END