CREATE DEFINER=`root`@`localhost` PROCEDURE `SP_NOTIFICATION_GROUP_DELETE`(
	IN P_NOTIFICATION_GROUP_ID INT
)
BEGIN
	DECLARE ERRO INT DEFAULT 0;
    DECLARE MENSAGEM VARCHAR(100) DEFAULT 'SUCESSO';
    DECLARE DELETED_ID INT DEFAULT 0;
    
    DECLARE EXIT HANDLER FOR SQLEXCEPTION
    BEGIN
		ROLLBACK;
        SELECT
			1 AS ERRO,
            'ERRO AO EXCLUIR GRUPO DE NOTIFICAÇÃO' AS MENSAGEM,
            0 AS ID;  
		END;
    
    START TRANSACTION;
		DELETE FROM NOTIFICATION_GROUP NG
        WHERE NG.ID = P_NOTIFICATION_GROU_ID;
    COMMIT;
    
    SELECT
		ERRO,
        MENSAGEM,
		NOTIFICATION_GROUP_ID AS ID;
END