CREATE DEFINER=`root`@`localhost` PROCEDURE `SP_NOTIFICATION_GROUP_GET_ALL`()
BEGIN
	SELECT
		NG.ID,
        NG.NAME,
        NG.IS_ACTIVE AS IsActive,
        NG.CREATED_AT AS CreatedAt,
        NG.UPDATED_AT AS UpdatedAt,
        CASE
			WHEN COUNT(NGE.ID) = 0 THEN NULL
			ELSE JSON_ARRAYAGG(
				JSON_OBJECT(
					'Id', NGE.ID,
					'Name', NGE.EMAIL
				)
			) END AS EmailsJSON
	FROM NOTIFICATION_GROUP NG
    LEFT JOIN NOTIFICATION_GROUP_EMAIL NGE ON NGE.NOTIFICATION_GROUP_ID = NG.ID
    GROUP BY
		NG.ID,
        NG.NAME,
        NG.IS_ACTIVE,
        NG.CREATED_AT,
        NG.UPDATED_AT;
END