CREATE DEFINER=`root`@`localhost` PROCEDURE `SP_NOTIFICATION_GROUP_CREATE`(
	IN P_NAME VARCHAR(30),
    IN P_EMAILS_JSON JSON
)
BEGIN
	DECLARE ERRO INT DEFAULT 0;
    DECLARE MENSAGEM VARCHAR(100) DEFAULT 'SUCESSO';
    DECLARE NEW_ID INT DEFAULT 0;
    
    DECLARE EXIT HANDLER FOR SQLEXCEPTION
    BEGIN
		ROLLBACK;
        SELECT 
			1 AS ERRO,
            'ERRO AO INSERIR GRUPO DE NOTIFICADAO' AS MENSAGEM,
            0 AS ID;
	END;
        
	START TRANSACTION;
		INSERT INTO NOTIFICATION_GROUP(NAME)
        VALUES (P_NAME);
        
        SET NEW_ID = LAST_INSERT_ID();
        
        INSERT INTO NOTIFICATION_GROUP_EMAIL(NOTIFICATION_GROUP_ID, EMAIL)
        SELECT NEW_ID, jt.email
        FROM JSON_TABLE(P_EMAILS_JSON, '$[*]' COLUMNS (email VARCHAR(100) PATH '$')) jt;
        
    COMMIT;
    
    SELECT 
		ERRO AS Erro,
        MENSAGEM AS Mensagem,
        NEW_ID AS Id;

END