CREATE DEFINER=`root`@`localhost` PROCEDURE `SP_NOTIFICATION_GROUP_UPDATE`(
	IN P_NOTIFICATION_GROUP_ID INT,
	IN P_NEW_EMAILS_JSON JSON,
	IN P_DELETE_EMAILS_JSON JSON
)
BEGIN
	DECLARE ERRO INT DEFAULT 0;
    DECLARE MENSAGEM VARCHAR(100) DEFAULT 'SUCESSO';
    DECLARE DELETED_ID INT DEFAULT 0;
    
    DECLARE EXIT HANDLER FOR SQLEXCEPTION
    BEGIN
		ROLLBACK;
        SELECT
			0 AS ERRO,
            'HOUVE UM ERRO AO EXCLUIR EMAILS' AS MENSAGEM,
            0 AS ID;
	END;
    
    INSERT INTO NOTIFICATION_GROUP_EMAIL(NOTIFICATION_GROUP_ID, EMAIL)
    SELECT P_NOTIFICATION_GROUP_ID, jt.email
    FROM JSON_TABLE(P_NEW_EMAILS_JSON, '$[*]' COLUMNS(email varchar(100) PATH '$')) jt;
    
    DELETE NGE
    FROM NOTIFICATION_GROUP_EMAIL NGE
    JOIN JSON_TABLE(
		P_DELETE_EMAILS_JSON,
        '$[*]' COLUMNS (
			id INT PATH '$'
        )
    ) jt
    ON jt.id = NGE.ID;

END